apiVersion: apps/v1
kind: Deployment
metadata:
  name: parcial-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parcial
  template:
    metadata:
      labels:
        app: parcial
    spec:
      containers:
        - name: parcial-app
          image: parcial-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8089
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/parcial"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: parcial-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
  selector:
    app: parcial
  type: LoadBalancer